package com.workerledger.app;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Pattern;

final class LedgerRepository {
    private static final int VERSION=2; private static final long MAX_SAFE=9007199254740991L;
    private static final Pattern DATE=Pattern.compile("\\d{4}-\\d{2}-\\d{2}"), MONTH=Pattern.compile("\\d{4}-\\d{2}");
    private final LedgerDbHelper helper;
    LedgerRepository(Context context){helper=new LedgerDbHelper(context);}
    synchronized String loadSnapshot() throws JSONException{return snapshot(helper.getReadableDatabase()).toString();}
    synchronized String exportSnapshot(String appVersion) throws JSONException {JSONObject s=snapshot(helper.getReadableDatabase());s.put("exportedAt",System.currentTimeMillis());s.put("appVersion",appVersion==null?"":appVersion);return s.toString();}
    synchronized String previewImport(String json) throws JSONException {JSONObject s=normalize(json); Validated v=validateSnapshot(s); JSONObject p=new JSONObject().put("schemaVersion",VERSION).put("exportedAt",s.opt("exportedAt")).put("entryCount",v.entries.length).put("salaryHistoryCount",v.history.length());String start=null,end=null;for(LedgerModels.Entry e:v.entries){if(start==null||e.entryDate.compareTo(start)<0)start=e.entryDate;if(end==null||e.entryDate.compareTo(end)>0)end=e.entryDate;}p.put("dateRange",start==null?JSONObject.NULL:new JSONObject().put("start",start).put("end",end));return p.put("snapshot",s).toString();}
    synchronized void saveSettings(LedgerModels.Settings s) throws JSONException {validateSettings(s);if(s.salaryEffectiveMonth!=null&&(!validMonth(s.salaryEffectiveMonth)||s.salaryEffectiveMonth.compareTo(currentMonth())>0))throw new IllegalArgumentException("工资生效月份无效");s.updatedAt=System.currentTimeMillis();SQLiteDatabase db=helper.getWritableDatabase();db.beginTransaction();try{db.update("user_settings",settingsValues(s),"id = ?",new String[]{"1"});if(s.salaryEffectiveMonth!=null)upsertSalary(db,s.salaryEffectiveMonth,s.monthlyTakeHomeCents,s.updatedAt,s.updatedAt);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    synchronized long insertEntry(LedgerModels.Entry e){validateEntry(e,false);long now=System.currentTimeMillis();e.createdAt=now;e.updatedAt=now;e.hourlyRateCentsPerHour=hourlyRate(settingsUnchecked(helper.getReadableDatabase()));return helper.getWritableDatabase().insertOrThrow("ledger_entries",null,entryValues(e,false));}
    synchronized void updateEntry(LedgerModels.Entry e){if(e==null||e.id<=0)throw new IllegalArgumentException("流水 ID 无效");SQLiteDatabase db=helper.getWritableDatabase();LedgerModels.Entry old=find(db,e.id);if(old==null)throw new IllegalArgumentException("找不到要更新的流水");e.createdAt=old.createdAt;e.updatedAt=System.currentTimeMillis();e.hourlyRateCentsPerHour=old.hourlyRateCentsPerHour;validateEntry(e,false);if(db.update("ledger_entries",entryValues(e,false),"_id = ?",new String[]{String.valueOf(e.id)})!=1)throw new IllegalArgumentException("找不到要更新的流水");}
    synchronized LedgerModels.Entry deleteEntry(long id){if(id<=0)throw new IllegalArgumentException("流水 ID 无效");SQLiteDatabase db=helper.getWritableDatabase();LedgerModels.Entry e=find(db,id);if(e==null||db.delete("ledger_entries","_id = ?",new String[]{String.valueOf(id)})!=1)throw new IllegalArgumentException("找不到要删除的流水");return e;}
    synchronized void restoreEntry(LedgerModels.Entry e){validateEntry(e,true);if(e.id<=0||find(helper.getReadableDatabase(),e.id)!=null)throw new IllegalArgumentException("流水无法恢复");helper.getWritableDatabase().insertOrThrow("ledger_entries",null,entryValues(e,true));}
    synchronized void replaceFromSnapshot(String json) throws JSONException {Validated v=validateSnapshot(normalize(json));SQLiteDatabase db=helper.getWritableDatabase();db.beginTransaction();try{db.delete("ledger_entries",null,null);db.delete("salary_history",null,null);db.insertWithOnConflict("user_settings",null,settingsValues(v.settings),SQLiteDatabase.CONFLICT_REPLACE);for(int i=0;i<v.history.length();i++){JSONObject h=v.history.getJSONObject(i);upsertSalary(db,h.getString("effectiveMonth"),LedgerModels.safeInteger(h,"monthlyTakeHomeCents"),LedgerModels.safeInteger(h,"createdAt"),LedgerModels.safeInteger(h,"updatedAt"));}for(LedgerModels.Entry e:v.entries)db.insertOrThrow("ledger_entries",null,entryValues(e,true));db.setTransactionSuccessful();}finally{db.endTransaction();}}
    private JSONObject snapshot(SQLiteDatabase db) throws JSONException {JSONObject s=new JSONObject().put("schemaVersion",VERSION).put("settings",readSettings(db).toJson());JSONArray h=new JSONArray(),e=new JSONArray();try(Cursor c=db.query("salary_history",null,null,null,null,null,"effective_month ASC")){while(c.moveToNext())h.put(new JSONObject().put("effectiveMonth",c.getString(c.getColumnIndexOrThrow("effective_month"))).put("monthlyTakeHomeCents",c.getLong(c.getColumnIndexOrThrow("monthly_take_home_cents"))).put("createdAt",c.getLong(c.getColumnIndexOrThrow("created_at"))).put("updatedAt",c.getLong(c.getColumnIndexOrThrow("updated_at"))));}try(Cursor c=db.query("ledger_entries",null,null,null,null,null,"entry_date DESC, created_at DESC")){while(c.moveToNext())e.put(readEntry(c).toJson());}return s.put("salaryHistory",h).put("entries",e);}
    private JSONObject normalize(String json) throws JSONException {JSONObject s=new JSONObject(json);if(s.has("schemaVersion")){if(LedgerModels.safeInteger(s,"schemaVersion")!=VERSION)throw new IllegalArgumentException("不支持的备份版本");return s;}JSONObject settings=s.getJSONObject("settings");JSONArray entries;if(!s.has("entries")){entries=new JSONArray();}else if(s.get("entries") instanceof JSONArray){entries=s.getJSONArray("entries");}else{throw new IllegalArgumentException("流水必须是数组");}long now=System.currentTimeMillis();s.put("schemaVersion",VERSION).put("entries",entries).put("exportedAt",now).put("salaryHistory",new JSONArray().put(new JSONObject().put("effectiveMonth",currentMonth()).put("monthlyTakeHomeCents",LedgerModels.safeInteger(settings,"monthlyTakeHomeCents")).put("createdAt",now).put("updatedAt",now)));for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);if(!e.has("hourlyRateCentsPerHour"))e.put("hourlyRateCentsPerHour",JSONObject.NULL);if(!e.has("createdAt"))e.put("createdAt",now);if(!e.has("updatedAt"))e.put("updatedAt",now);}return s;}
    private Validated validateSnapshot(JSONObject s) throws JSONException {if(LedgerModels.safeInteger(s,"schemaVersion")!=VERSION)throw new IllegalArgumentException("不支持的备份版本");LedgerModels.Settings settings=LedgerModels.Settings.fromJson(s.getJSONObject("settings"));validateSettings(settings);timestamp(settings.updatedAt);JSONArray h=s.getJSONArray("salaryHistory");Set<String> months=new HashSet<>();for(int i=0;i<h.length();i++){JSONObject x=h.getJSONObject(i);if(!validMonth(x.getString("effectiveMonth"))||!months.add(x.getString("effectiveMonth"))||!nonNegative(LedgerModels.safeInteger(x,"monthlyTakeHomeCents")))throw new IllegalArgumentException("工资历史无效");timestamp(LedgerModels.safeInteger(x,"createdAt"));timestamp(LedgerModels.safeInteger(x,"updatedAt"));}JSONArray a=s.getJSONArray("entries");LedgerModels.Entry[] entries=new LedgerModels.Entry[a.length()];Set<Long> ids=new HashSet<>();for(int i=0;i<a.length();i++){entries[i]=LedgerModels.Entry.fromJson(a.getJSONObject(i));if(!positive(entries[i].id)||!ids.add(entries[i].id))throw new IllegalArgumentException("导入流水 ID 无效或重复");validateEntry(entries[i],true);}if(s.has("exportedAt")&&!s.isNull("exportedAt"))timestamp(LedgerModels.safeInteger(s,"exportedAt"));return new Validated(settings,entries,h);}
    private LedgerModels.Settings readSettings(SQLiteDatabase db) throws JSONException {try(Cursor c=db.query("user_settings",null,"id = ?",new String[]{"1"},null,null,null)){if(!c.moveToFirst())throw new IllegalStateException("设置记录缺失");LedgerModels.Settings s=new LedgerModels.Settings();s.monthlyTakeHomeCents=c.getLong(c.getColumnIndexOrThrow("monthly_take_home_cents"));s.payMonths=c.getDouble(c.getColumnIndexOrThrow("pay_months"));s.workdaysPerMonth=c.getDouble(c.getColumnIndexOrThrow("workdays_per_month"));s.onsiteHoursPerDay=c.getDouble(c.getColumnIndexOrThrow("onsite_hours_per_day"));s.commuteHoursPerDay=c.getDouble(c.getColumnIndexOrThrow("commute_hours_per_day"));s.overtimeHoursPerMonth=c.getDouble(c.getColumnIndexOrThrow("overtime_hours_per_month"));s.workCostCentsPerMonth=c.getLong(c.getColumnIndexOrThrow("work_cost_cents_per_month"));s.fundGoalCents=c.getLong(c.getColumnIndexOrThrow("fund_goal_cents"));s.fundCurrentCents=c.getLong(c.getColumnIndexOrThrow("fund_current_cents"));s.updatedAt=c.getLong(c.getColumnIndexOrThrow("updated_at"));return s;}}
    private LedgerModels.Settings settingsUnchecked(SQLiteDatabase db){try{return readSettings(db);}catch(JSONException e){throw new IllegalStateException(e);}}
    private LedgerModels.Entry find(SQLiteDatabase db,long id){try(Cursor c=db.query("ledger_entries",null,"_id = ?",new String[]{String.valueOf(id)},null,null,null)){return c.moveToFirst()?readEntry(c):null;}}
    private LedgerModels.Entry readEntry(Cursor c){LedgerModels.Entry e=new LedgerModels.Entry();e.id=c.getLong(c.getColumnIndexOrThrow("_id"));e.kind=c.getString(c.getColumnIndexOrThrow("kind"));e.amountCents=c.getLong(c.getColumnIndexOrThrow("amount_cents"));e.category=c.getString(c.getColumnIndexOrThrow("category"));e.note=c.getString(c.getColumnIndexOrThrow("note"));e.entryDate=c.getString(c.getColumnIndexOrThrow("entry_date"));e.expenseType=c.getString(c.getColumnIndexOrThrow("expense_type"));e.createdAt=c.getLong(c.getColumnIndexOrThrow("created_at"));e.updatedAt=c.getLong(c.getColumnIndexOrThrow("updated_at"));int r=c.getColumnIndexOrThrow("hourly_rate_cents_per_hour");e.hourlyRateCentsPerHour=c.isNull(r)?null:c.getLong(r);return e;}
    private ContentValues settingsValues(LedgerModels.Settings s){ContentValues v=new ContentValues();v.put("id",1);v.put("monthly_take_home_cents",s.monthlyTakeHomeCents);v.put("pay_months",s.payMonths);v.put("workdays_per_month",s.workdaysPerMonth);v.put("onsite_hours_per_day",s.onsiteHoursPerDay);v.put("commute_hours_per_day",s.commuteHoursPerDay);v.put("overtime_hours_per_month",s.overtimeHoursPerMonth);v.put("work_cost_cents_per_month",s.workCostCentsPerMonth);v.put("fund_goal_cents",s.fundGoalCents);v.put("fund_current_cents",s.fundCurrentCents);v.put("updated_at",s.updatedAt);return v;}
    private ContentValues entryValues(LedgerModels.Entry e,boolean id){ContentValues v=new ContentValues();if(id)v.put("_id",e.id);v.put("kind",e.kind);v.put("amount_cents",e.amountCents);v.put("category",e.category.trim());v.put("note",e.note==null?"":e.note.trim());v.put("entry_date",e.entryDate);if("income".equals(e.kind))v.putNull("expense_type");else v.put("expense_type",e.expenseType);if(e.hourlyRateCentsPerHour==null)v.putNull("hourly_rate_cents_per_hour");else v.put("hourly_rate_cents_per_hour",e.hourlyRateCentsPerHour);v.put("created_at",e.createdAt);v.put("updated_at",e.updatedAt);return v;}
    private void upsertSalary(SQLiteDatabase db,String month,long salary,long createdAt,long updatedAt){ContentValues v=new ContentValues();v.put("effective_month",month);v.put("monthly_take_home_cents",salary);v.put("created_at",createdAt);v.put("updated_at",updatedAt);db.insertWithOnConflict("salary_history",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    private Long hourlyRate(LedgerModels.Settings s){double hours=s.workdaysPerMonth*(s.onsiteHoursPerDay+s.commuteHoursPerDay)+s.overtimeHoursPerMonth,rate=s.monthlyTakeHomeCents*(double)s.payMonths/(12d*hours);return s.monthlyTakeHomeCents>0&&hours>0&&Double.isFinite(rate)&&rate>0&&rate<=MAX_SAFE?Math.round(rate):null;}
    private void validateSettings(LedgerModels.Settings s){if(s==null||!nonNegative(s.monthlyTakeHomeCents)||!nonNegative(s.workCostCentsPerMonth)||!nonNegative(s.fundGoalCents)||!nonNegative(s.fundCurrentCents)||!finite(s.payMonths)||!finite(s.workdaysPerMonth)||!finite(s.onsiteHoursPerDay)||!finite(s.commuteHoursPerDay)||!finite(s.overtimeHoursPerMonth)||s.payMonths<=0||s.workdaysPerMonth<=0||s.onsiteHoursPerDay+s.commuteHoursPerDay<=0)throw new IllegalArgumentException("时薪设置必须是有效的非负数字，并且工作时间大于 0");}
    private void validateEntry(LedgerModels.Entry e,boolean times){if(e==null||(!"income".equals(e.kind)&&!"expense".equals(e.kind)))throw new IllegalArgumentException("流水类型无效");if(!positive(e.amountCents)||e.category==null||e.category.trim().isEmpty()||!validDate(e.entryDate))throw new IllegalArgumentException("流水金额、分类或日期无效");if("expense".equals(e.kind)&&!"fixed".equals(e.expenseType)&&!"flexible".equals(e.expenseType))throw new IllegalArgumentException("支出类型无效");if("income".equals(e.kind)&&e.expenseType!=null&&!e.expenseType.isEmpty())throw new IllegalArgumentException("收入不能设置固定或弹性");if(e.hourlyRateCentsPerHour!=null&&!positive(e.hourlyRateCentsPerHour))throw new IllegalArgumentException("历史时薪无效");if(times){timestamp(e.createdAt);timestamp(e.updatedAt);}}
    private boolean validDate(String s){return valid(s,DATE,"yyyy-MM-dd");}private boolean validMonth(String s){return valid(s,MONTH,"yyyy-MM");}private boolean valid(String s,Pattern p,String f){if(s==null||!p.matcher(s).matches())return false;SimpleDateFormat d=new SimpleDateFormat(f,Locale.US);GregorianCalendar calendar=new GregorianCalendar(Locale.US);calendar.setGregorianChange(new Date(Long.MIN_VALUE));d.setCalendar(calendar);d.setLenient(false);try{return s.equals(d.format(d.parse(s)));}catch(ParseException e){return false;}}private boolean finite(double n){return Double.isFinite(n)&&n>=0;}private boolean positive(long n){return n>0&&n<=MAX_SAFE;}private boolean nonNegative(long n){return n>=0&&n<=MAX_SAFE;}private void timestamp(long n){if(!positive(n))throw new IllegalArgumentException("时间戳无效");}private String currentMonth(){return new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());}
    private static final class Validated{final LedgerModels.Settings settings;final LedgerModels.Entry[] entries;final JSONArray history;Validated(LedgerModels.Settings s,LedgerModels.Entry[] e,JSONArray h){settings=s;entries=e;history=h;}}
}
